--> generated by p8import.py
function create_rooms()
	add_room({ origin=vec2(0, 0), size=vec2(16, 16), layers={ "bg", "bg", "fg" }})
	add_room({ origin=vec2(48, 0), size=vec2(16, 16), layers={ "bg", "bg", "fg" }})
end